config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index'
  root to: "tweets#index"

  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :nickname, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path(@tweet)
    else
      render new_tweet_path
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      redirect_to root_path
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to root_path
    else
      render edit_tweet_path
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:nickname, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>つぶやきの場</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left"><%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
            <div class="nav__right">
              <%= link_to "ログアウト", "#", method: :delete, class: :nav__logout %>
              <%= link_to "投稿する", new_tweet_path, class: :nav__btn %>
            </div>
            <div class="nav__right">
              <%= link_to "ログイン", "#", class: :nav__btn %>
              <%= link_to "新規登録", "#", class: :nav__btn %>
            </div>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
    <h2 class="page-heading">編集する</h2>
    <%= form_with model: @tweet, local: true do |form| %>
      <div class = "field">
        <%= form.label :nickname, "ニックネーム" %><br />
        <%= form.text_field :nickname, placeholder: "nickname" %>
      </div>
      <div class = "field">
        <%= form.label :text, "つぶやきたい事" %><br />
        <%= form.text_area :text, placeholder: "text", rows: "10" %>
      </div>
      <div class = "actions">
        <%= form.submit "SEND" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<main class="main">
  <div class="inner">
    <% @tweets.each do |tweet| %>
    <div class="card">
      <div class="card__body">
        <%= link_to tweet.nickname, "#", class: :card__nickname%>
        <p class="card__summary">
          <%= tweet.text %>
        </p>
        <ul>
          <li>
            <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
          </li>
        </ul>
      </div>
    </div>
    <% end %>
  </div>
</main>

  </div>
</main>

app/views/tweets/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
    <h2 class="page-heading">投稿する</h2>
    <%= form_with model: @tweet, local: true do |form| %>
      <div class = "field">
        <%= form.label :nickname, "ニックネーム" %><br />
        <%= form.text_field :nickname, placeholder: "nickname" %>
      </div>
      <div class = "field">
        <%= form.label :text, "つぶやきたい事" %><br />
        <%= form.text_area :text, placeholder: "text", rows: "10" %>
      </div>
      <div class = "actions">
        <%= form.submit "SEND" %>
      </div>
    <% end %>
  </div>
</div>